'use client'

import Link from 'next/link'
import { useState } from 'react'
import { AlertTriangle, ArrowDownRight, ArrowLeft, Check, CircleAlert, Sparkles } from 'lucide-react'

const initialAlerts = [{ id: 1, title: 'Concentração excessiva', text: 'ITUB4 representa 24,2% da carteira, acima do limite recomendado.', type: 'warning', time: 'Hoje, 09:42' }, { id: 2, title: 'Oportunidade nova', text: 'TAEE11 entrou no radar com score 91 e valuation em desconto.', type: 'positive', time: 'Hoje, 08:15' }, { id: 3, title: 'Mudança no cenário macro', text: 'A leitura de juros alterou a confiança das análises de curto prazo.', type: 'neutral', time: 'Ontem, 18:30' }]

export default function AlertsPage() { const [alerts, setAlerts] = useState(initialAlerts); return <main className="min-h-screen bg-background p-5 text-foreground sm:p-8 lg:p-10"><div className="mx-auto max-w-5xl"><Link href="/" className="inline-flex items-center gap-2 text-sm text-muted-foreground hover:text-foreground"><ArrowLeft className="size-4" />Visão geral</Link><div className="mt-8 flex items-end justify-between gap-4"><div><p className="font-mono text-xs uppercase tracking-[0.2em] text-primary">ATLAS · monitoramento</p><h1 className="mt-3 text-4xl font-semibold tracking-tight">Alertas</h1><p className="mt-2 text-muted-foreground">Mudanças importantes na carteira e nas análises.</p></div><button onClick={() => setAlerts([])} className="rounded-lg border border-border px-3 py-2 text-xs text-muted-foreground hover:bg-muted">Marcar todos como lidos</button></div><div className="mt-8 flex flex-col gap-3">{alerts.map((alert) => <article key={alert.id} className="flex gap-4 rounded-2xl border border-border bg-card p-5"><div className={`flex size-10 shrink-0 items-center justify-center rounded-xl ${alert.type === 'positive' ? 'bg-primary/10 text-primary' : 'bg-accent text-accent-foreground'}`}>{alert.type === 'positive' ? <Sparkles className="size-5" /> : alert.type === 'warning' ? <AlertTriangle className="size-5" /> : <ArrowDownRight className="size-5" />}</div><div className="flex-1"><div className="flex items-start justify-between gap-4"><div><h2 className="font-medium">{alert.title}</h2><p className="mt-2 text-sm leading-6 text-muted-foreground">{alert.text}</p></div><span className="whitespace-nowrap text-xs text-muted-foreground">{alert.time}</span></div></div></article>)}{!alerts.length && <div className="rounded-2xl border border-dashed border-border p-12 text-center"><Check className="mx-auto size-6 text-primary" /><p className="mt-3 text-sm">Tudo em dia por aqui.</p><p className="mt-1 text-xs text-muted-foreground">Novos alertas aparecerão após a próxima análise.</p></div>}</div><div className="mt-8 grid gap-3 sm:grid-cols-3"><div className="rounded-2xl border border-border bg-card p-4"><CircleAlert className="size-4 text-primary" /><p className="mt-4 text-2xl font-semibold">03</p><p className="text-xs text-muted-foreground">Alertas ativos</p></div><div className="rounded-2xl border border-border bg-card p-4"><ArrowDownRight className="size-4 text-muted-foreground" /><p className="mt-4 text-2xl font-semibold">01</p><p className="text-xs text-muted-foreground">Mudança de score</p></div><div className="rounded-2xl border border-border bg-card p-4"><Sparkles className="size-4 text-primary" /><p className="mt-4 text-2xl font-semibold">01</p><p className="text-xs text-muted-foreground">Nova oportunidade</p></div></div></div></main> }
